'use client';

import { createClient } from '@neondatabase/neon-js';
import { BetterAuthReactAdapter } from '@neondatabase/neon-js/auth/react/adapters';
import type { Priority } from './validation';

/**
 * Shape of the database, used to type the Data API query builder.
 * Mirrors db/schema.sql.
 */
export type Database = {
  public: {
    Tables: {
      contacts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          company: string | null;
          role: string | null;
          where_met: string | null;
          notes: string | null;
          priority: Priority;
          /** Generated by Postgres: high = 1, medium = 2, low = 3. Read-only. */
          priority_rank: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          company?: string | null;
          role?: string | null;
          where_met?: string | null;
          notes?: string | null;
          priority: Priority;
        };
        Update: {
          name?: string;
          company?: string | null;
          role?: string | null;
          where_met?: string | null;
          notes?: string | null;
          priority?: Priority;
        };
      };
    };
  };
};

export type Contact = Database['public']['Tables']['contacts']['Row'];

/**
 * These two URLs are public by design -- they are compiled into the browser
 * bundle. They are endpoints, not credentials: Row Level Security is what keeps
 * one user out of another user's rows, not the secrecy of these strings.
 *
 * Referenced as full literals because Next.js only inlines NEXT_PUBLIC_ vars
 * when it can see the complete `process.env.NAME` expression at build time.
 */
const AUTH_URL = process.env.NEXT_PUBLIC_NEON_AUTH_URL;
const DATA_API_URL = process.env.NEXT_PUBLIC_NEON_DATA_API_URL;

type NeonClient = ReturnType<typeof buildClient>;

function buildClient() {
  if (!AUTH_URL || !DATA_API_URL) {
    throw new Error(
      'Missing Neon configuration. Copy .env.example to .env.local and set ' +
        'NEXT_PUBLIC_NEON_AUTH_URL and NEXT_PUBLIC_NEON_DATA_API_URL.',
    );
  }

  return createClient<Database>({
    auth: {
      url: AUTH_URL,
      // The React adapter is what exposes useSession() as a hook and keeps
      // session state in sync across tabs.
      adapter: BetterAuthReactAdapter(),
    },
    dataApi: { url: DATA_API_URL },
  });
}

let client: NeonClient | null = null;

/**
 * Built on first use rather than at module load, so that a missing environment
 * variable surfaces as a readable message in the UI instead of breaking the
 * production build.
 */
export function getNeonClient(): NeonClient {
  client ??= buildClient();
  return client;
}

export function isNeonConfigured(): boolean {
  return Boolean(AUTH_URL && DATA_API_URL);
}
